---
- name: Validate tripleo-modify-image changes
  hosts: compute
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: Validate the container get update image with "latest-hotfix" tag
      shell: |
        podman ps |grep {{ test.tripleo.modify.container }}
      register: containers_list
      failed_when: '"-hotfix" not in containers_list.stdout'
      become: true
      become_method: sudo
